# Generated by `ryra org machines export-secrets`. Do not edit: the next deploy
# overwrites this file.
#
# Empty in the template, and it has to exist: a module list naming a file that is
# not there does not evaluate, so a machine could not be built until it had been
# deployed to once. The same reason `secrets.nix` ships empty beside it.
#
# What lands here is the accounts the organization declares for this machine, and
# the certificate authority it signs with. A template that carried either would be
# a template that let its author into every machine started from it.
{ ... }:
{
}
