# Generated by `ryra org machines export-secrets`. Do not edit: the next deploy
# overwrites this file.
#
# Which secrets belong here is derived rather than declared twice: a secret names
# the groups that should have it, a machine names the groups that may log in, and
# where those overlap the secret has somewhere to be.
#
# Empty in the template, and imported anyway. A module list naming a file that is
# not there does not evaluate, so a machine has to be buildable before it has
# ever been deployed to.
{ ... }:
{
}
